version: "3"

services:

  ricardo-backend:
    image: ricardo-backend
    container_name: ricardo-backend
    user: "${UID}:${GID}"
    environment:
      - RICARDO_BACKEND_DEVICE=${SERIAL_PATH}
    ports:
      - 1337:1337
      - 1338:1338
    volumes:
      - ./Config/:/ricardo-backend/Config/
      - ./volumes/ricardo-backend/logs/:/ricardo-backend/Logs/
    devices:
      - ${SERIAL_PATH}:${SERIAL_PATH}
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: "${UID}:${GID}"
    environment:
      - GF_INSTALL_PLUGINS=golioth-websocket-datasource,agenty-flowcharting-panel
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana/grafana.db:/var/lib/grafana/grafana.db
      - ./volumes/grafana/plugins/:/var/lib/grafana/plugins/
    restart: always

  caddy:
    image: caddy
    container_name: caddy
    user: "${UID}:${GID}"
    environment:
      - RICARDO_BACKEND_DOMAIN=${RICARDO_BACKEND_DOMAIN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: always
