version: "3"

services:

  ricardo-backend:
    image: ricardo-backend
    container_name: ricardo-backend
    user: "${UID}:${GID}"
    environment:
      - RICARDO_BACKEND_DEVICE=/dev/ricardo_device
      - RICARDO_BACKEND_FAKE_DATA=TRUE
    ports:
      - 1337:1337
    volumes:
      - ./volumes/ricardo-backend/logs/:/Logs/
    networks:
      - backend
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: "${UID}:${GID}"
    environment:
      - GF_INSTALL_PLUGINS=golioth-websocket-datasource,agenty-flowcharting-panel
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana/grafana.db:/var/lib/grafana/grafana.db
      - ./volumes/grafana/plugins/:/var/lib/grafana/plugins/
    networks:
      - backend
    restart: always

networks:
  backend:
    external: false
