version: "3"

services:

  ricardo-backend:
    image: ricardo-backend
    container_name: ricardo-backend
    environment:
      - RICARDO_BACKEND_DEVICE=/dev/ricardo_device
      - RICARDO_BACKEND_FAKE_DATA=TRUE
    ports:
      - 1337:1337
    devices:
      - /dev/ttyUSB0:/dev/ricardo_device
    networks:
      - backend
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=golioth-websocket-datasource,agenty-flowcharting-panel
    ports:
      - 3000:3000
    volumes:
      - ./Config/grafana/grafana.db:/var/lib/grafana/grafana.db
      - ./Config/grafana/plugins/:/var/lib/grafana/plugins/
    networks:
      - backend
    restart: always

networks:
  backend:
    external: false
