version: "3"

services:

  ricardo-backend:
    image: ricardo-backend
    build:
      context: .
    container_name: ricardo-backend
    user: "${UID}:${GID}"
    environment:
      - RICARDO_BACKEND_DEVICE=${SERIAL_PATH}
    ports:
      - 1337:1337
      - 1338:1338
    volumes:
      - ./Config/:/ricardo-backend/Config/
      - ./volumes/ricardo-backend/logs/:/ricardo-backend/Logs/
    devices:
      - ${SERIAL_PATH}:${SERIAL_PATH}
    restart: unless-stopped

  grafana:
    image: grafana-iclr
    build:
      context: ./external/grafana
      args:
        - GF_INSTALL_PLUGINS=golioth-websocket-datasource,agenty-flowcharting-panel,speakyourcode-button-panel,grafana-clock-panel,yesoreyeram-infinity-datasource
    container_name: grafana
    user: "${UID}:${GID}"
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana/grafana.db:/var/lib/grafana/grafana.db
    restart: unless-stopped

  caddy:
    image: caddy
    container_name: caddy
    user: "${UID}:${GID}"
    environment:
      - RICARDO_BACKEND_DOMAIN=${RICARDO_BACKEND_DOMAIN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
